name: Jules Tolentino
favicon: null
layout_spectrum: 0.8228135020472109
typography_spectrum: 0.26256928918883204
title: Diamonds in the Rough
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.14680762006901205
  lightness: 0.9629622695501894
  saturation: 0.05881572887301445
  rhythmicContrast: 0.5618727263063192
purpose: []
